apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mysql
  name: mysql
spec:
  containers:
    - image: sarthaksatish/mysql:v1
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: test
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
