FROM mysql:8.0.33
LABEL "Project"="EmployeeManagement"
LABEL "Author"="Sarthak Satish"

# ENV MYSQL_ROOT_PASSWORD="test"
# ENV MYSQL_DATABASE="employees"

# ADD db_backup.sql docker-entrypoint-initdb.d/db_backup.sql

# EXPOSE 3306



