apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: employeemanagement
  name: employeemanagement
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employeemanagement
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: employeemanagement
    spec:
      initContainers:
        - name: init-mydb
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nslookup mysql-db.jenkins.svc.cluster.local; do echo waiting for mysql-db; sleep 2; done;",
            ]
      containers:
        - image: "sarthaksatish/employeemanagement:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          name: employeemanagement
          resources: {}
