apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-09-20T19:25:02Z"
  generation: 1
  labels:
    app: employeemanagement
  name: employeemanagement
  namespace: jenkins
  resourceVersion: "1981598"
  uid: 151856ed-7e74-4476-96f8-6769e3a9f0cf
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: employeemanagement
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: employeemanagement
    spec:
      initContainers:
        - name: init-mydb
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nslookup mysql-db.jenkins.svc.cluster.local; do echo waiting for mysql-db; sleep 2; done;",
            ]
      containers:
        - image: "sarthaksatish/employeemanagement:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          name: employeemanagement
          resources: {}
