apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gaganemployee
  name: gagansvc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: gaganemployee
status:
  loadBalancer: {}
