apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: employeemanagement
  name: employeemanagement
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: employeemanagement
status:
  loadBalancer: {}
